apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: myservice
spec:
  template:
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/credible-art-418518/gke-repo/batchrun-image:latest