apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: JOB
description: prod
requireApproval: true
spec:
  template:
    spec:
      template:
        spec:
          containers:
          - image: us-central1-docker.pkg.dev/credible-art-418518/gke-repo/batchrun-image:latest

